const data = [
    {
        "Table": "1",
        "Reward 1": "Kelbi Horn x1",
        "Reward 2": "Kelbi Horn x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Health Horn x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Health Horn x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Field Horn x1",
        "Reward 6": "Field Horn x1",
        "Reward 7": "Nulberry x3",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Health Horn x1",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Raw Meat x1",
        "Reward 5": "Health Horn x1",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Kelbi Horn x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "2",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "2",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Kelbi Horn x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "2",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "---",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "2",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "3",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Kelbi Horn x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "3",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "3",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "3",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "4",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "4",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "4",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "4",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Raw Meat x1",
        "Reward 5": "Raw Meat x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "5",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Health Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "5",
        "Reward 1": "Health Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "5",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "5",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "7",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "7",
        "Reward 1": "Kelbi Horn x1",
        "Reward 2": "Kelbi Horn x1",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "---",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "7",
        "Reward 1": "Nulberry x3",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Kelbi Horn x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Raw Meat x1",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "8",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "8",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "8",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Field Horn x1",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "8",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "8",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "9",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "9",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "9",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "10",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "10",
        "Reward 1": "Kelbi Horn x1",
        "Reward 2": "Kelbi Horn x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "10",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "10",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Kelbi Horn x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "10",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Raw Meat x1",
        "Reward 5": "Raw Meat x1",
        "Reward 6": "Field Horn x1",
        "Reward 7": "Nulberry x3",
        "Reward 8": "Nulberry x3",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "11",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    },
    {
        "Table": "11",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "11",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "12",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2"
    },
    {
        "Table": "12",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---"
    }
]