const data = [
    {
        "Table": "1",
        "Reward 1": "Kelbi Horn x1",
        "Reward 2": "Kelbi Horn x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "56"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Health Horn x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "16"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Health Horn x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "2"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "57"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "7"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "50"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "41"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Field Horn x1",
        "Reward 6": "Field Horn x1",
        "Reward 7": "Nulberry x3",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "45"
    },
    {
        "Table": "1",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Raw Meat x1",
        "Reward 5": "Health Horn x1",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Kelbi Horn x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "44"
    },
    {
        "Table": "2",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "40"
    },
    {
        "Table": "2",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Kelbi Horn x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "36"
    },
    {
        "Table": "2",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "---",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "58"
    },
    {
        "Table": "2",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "5"
    },
    {
        "Table": "3",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Kelbi Horn x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "10"
    },
    {
        "Table": "3",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "47"
    },
    {
        "Table": "3",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "9"
    },
    {
        "Table": "3",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "35"
    },
    {
        "Table": "4",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "54"
    },
    {
        "Table": "4",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "46"
    },
    {
        "Table": "4",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "26"
    },
    {
        "Table": "4",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Raw Meat x1",
        "Reward 5": "Raw Meat x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "34"
    },
    {
        "Table": "5",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Health Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "6"
    },
    {
        "Table": "5",
        "Reward 1": "Health Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "48"
    },
    {
        "Table": "5",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "21"
    },
    {
        "Table": "5",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "37"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "32"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "14"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "4"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "39"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "51"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "11"
    },
    {
        "Table": "6",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "49"
    },
    {
        "Table": "7",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "31"
    },
    {
        "Table": "7",
        "Reward 1": "Kelbi Horn x1",
        "Reward 2": "Kelbi Horn x1",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x2",
        "Reward 5": "---",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "53"
    },
    {
        "Table": "7",
        "Reward 1": "Nulberry x3",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "27"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Kelbi Horn x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "59"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "13"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "17"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "30"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "23"
    },
    {
        "Table": "7",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Raw Meat x1",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "38"
    },
    {
        "Table": "8",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "29"
    },
    {
        "Table": "8",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Warm Pelt x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "43"
    },
    {
        "Table": "8",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Field Horn x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Field Horn x1",
        "Reward 6": "Nulberry x3",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "20"
    },
    {
        "Table": "8",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "18"
    },
    {
        "Table": "8",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "55"
    },
    {
        "Table": "9",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "52"
    },
    {
        "Table": "9",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "19"
    },
    {
        "Table": "9",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "Warm Pelt x2",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "15"
    },
    {
        "Table": "10",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "0"
    },
    {
        "Table": "10",
        "Reward 1": "Field Horn x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "1"
    },
    {
        "Table": "10",
        "Reward 1": "Kelbi Horn x1",
        "Reward 2": "Kelbi Horn x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "22"
    },
    {
        "Table": "10",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Warm Pelt x1",
        "Reward 5": "Warm Pelt x2",
        "Reward 6": "---",
        "Reward 7": "---",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "8"
    },
    {
        "Table": "10",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Field Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Kelbi Horn x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "25"
    },
    {
        "Table": "10",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Raw Meat x1",
        "Reward 4": "Raw Meat x1",
        "Reward 5": "Raw Meat x1",
        "Reward 6": "Field Horn x1",
        "Reward 7": "Nulberry x3",
        "Reward 8": "Nulberry x3",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "28"
    },
    {
        "Table": "11",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Health Horn x1",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Nulberry x3",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "42"
    },
    {
        "Table": "11",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Nulberry x3",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Warm Pelt x1",
        "Reward 6": "Warm Pelt x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "12"
    },
    {
        "Table": "11",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Warm Pelt x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x2",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "33"
    },
    {
        "Table": "12",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Field Horn x1",
        "Reward 3": "Kelbi Horn x1",
        "Reward 4": "Kelbi Horn x1",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Kelbi Horn x1",
        "Reward 7": "Kelbi Horn x1",
        "Reward 8": "Warm Pelt x1",
        "Reward 9": "Warm Pelt x1",
        "Reward 10": "Warm Pelt x2",
        "Seconds": "24"
    },
    {
        "Table": "12",
        "Reward 1": "Raw Meat x1",
        "Reward 2": "Raw Meat x1",
        "Reward 3": "Nulberry x3",
        "Reward 4": "Nulberry x3",
        "Reward 5": "Kelbi Horn x1",
        "Reward 6": "Warm Pelt x2",
        "Reward 7": "Warm Pelt x2",
        "Reward 8": "---",
        "Reward 9": "---",
        "Reward 10": "---",
        "Seconds": "3"
    }
]